apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-piggy
  namespace: be-namespace
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # 한 번에 다운될 수 있는 최대 개수 (1개)
      maxSurge: 1        # 한 번에 추가로 생성할 수 있는 최대 개수 (1개)
  selector:
    matchLabels:
      app: be-piggy
  template:
    metadata:
      labels:
        app: be-piggy
    spec:
      containers:
      - name: be-piggy
        image: jiwonchoe/piggybank-module:v1.93
        imagePullPolicy: Always  # ⭐️ 항상 최신 이미지로 업데이트
    env:
      - name: MY_URL
        value: "jdbc:mysql://mysql-master.db-namespace.svc.cluster.local:3306/test_db"
      - name: MY_USERNAME
        value: "root"
      - name: MY_PASSWORD
        value: ""
        ports:
        - containerPort: 80
