server:
  port: ${PORT}
spring:
  batch:
    jdbc:
      initialize-schema: always  # 스키마를 항상 초기화
    job:
      enabled: false
  datasource:
    url: ${MY_URL}
    username: ${MY_USERNAME}
    password: ${MY_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
#  redis:
#    host: ${REDIS_HOST}
#    port: ${REDIS_PORT}
#    password:
#
#appkey: ${APP_KEY}
#appsecret: ${APP_SECRET}
stock:
  api:
    base-url: "http://localhost:8081"
cloud:
  aws:
    s3:
      bucket: inst00ck-icebucket
      path:
        user : user
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}