#stock module
server:
  port: ${PORT}
  profiles: prod
spring:
  batch:
    jdbc:
      initialize-schema: always  # 스키마를 항상 초기화
    job:
      enabled: false
  datasource:
    url: ${MY_URL}
    username: ${MY_USERNAME}
    password: ${MY_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  kafka:
    producer:
      bootstrap-servers: ${SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS:localhost:9092,localhost:9094}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      properties:
        retry.backoff.ms: 1000
        delivery.timeout.ms: 12000
        linger.ms: 0
        request.timeout.ms: 3000
        max.in.flight.requests.per.connection: 5
        enable.idempotence: true
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS:localhost:9092,localhost:9094}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: community-group
      properties:
        spring.json.trusted.packages: "*"
community:
  commands:
    topic:
      checkStock: community.check-stock-topic
      finalizePost: community.finalize-post-topic
      rollbackPost: community.rollback-post-topic
  events:
    topic:
      finishedPost: community.finished-post-topic
      rollback: community.rollback-topic
#  redis:
#    host: ${REDIS_HOST}
#    port: ${REDIS_PORT}
#    password:
#
#appkey: ${APP_KEY}
#appsecret: ${APP_SECRET}
stock:
  api:
    base-url: "http://localhost:8081"
cloud:
  aws:
    s3:
      bucket: inst00ck-icebucket
      path:
        user : user
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
openai:
  api:
    key: ${OPENAI_KEY}

feign:
  piggyBank-url: ${PIGGYBANK_URL:localhost:8082}
  stock-url: ${STOCK_URL:localhost:8081}
  community-url: ${COMMUNITY_URL:localhost:8080}
