apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-community
  namespace: be-namespace
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # 한 번에 다운될 수 있는 최대 개수 (1개)
      maxSurge: 1        # 한 번에 추가로 생성할 수 있는 최대 개수 (1개)
  selector:
    matchLabels:
      app: be-community
  template:
    metadata:
      labels:
        app: be-community
    spec:
      containers:
      - name: be-community
        image: jiwonchoe/community-module:v1.2
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
